server:
  port: 9000
  servlet:
    context-path: /base
spring:
  application:
    name: novel-base
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/novel?useUnicode=true&characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull&generateSimpleParameterMetadata=true&autoReconnect=true
    username: root
    password: qiaojing123
    druid-pool:
     max-active: 20
     initial-size: 2
     max-wait: 60000
     min-idle: 2
mybatis-plus:
  mapper-locations: classpath*:/com/qj/novel/*/mapper/xml/*.xml
  configuration:
    #开启SQL语句打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰命名规则
    map-underscore-to-camel-case: true


