server:
  port: 9000
  servlet:
    context-path: /crawler
spring:
  application:
    name: novel-crawler
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/novel?useUnicode=true&characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull&generateSimpleParameterMetadata=true&autoReconnect=true
    username: root
    password: qiaojing123
    druid-pool:
     max-active: 20
     initial-size: 2
     max-wait: 60000
     min-idle: 2
mybatis-plus:
  mapper-locations: classpath*:/com/qj/novel/*/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 日志持久化 相关配置
logging:
  config: classpath:logback.xml
  file:
    name: ${user.dir}/logs/${spring.application.name}

